package export

import (
	"fmt"
	"strings"

	"github.com/lignumqt/envsnap/internal/snapshot"
)

// renderAnsible produces an Ansible playbook YAML that reproduces the captured
// environment.  It requires the community.general collection for modprobe tasks.
func renderAnsible(snap *snapshot.Snapshot, opts Options) (string, error) {
	var sb strings.Builder
	pm := packageManager(snap)
	ver := goVersion(snap)
	mods := activeMods(snap, opts.OnlyLoaded)
	if opts.SkipModules {
		mods = nil
	}
	date := snap.Meta.CreatedAt.UTC().Format("2006-01-02")

	// ── Header ───────────────────────────────────────────────────────────────
	fmt.Fprintf(&sb, "---\n")
	fmt.Fprintf(&sb, "# Generated by envsnap %s — export --format ansible\n", snap.Meta.ToolVersion)
	fmt.Fprintf(&sb, "# Source host: %s  user: %s  captured: %s\n",
		snap.Meta.Hostname, snap.Meta.User,
		snap.Meta.CreatedAt.UTC().Format("2006-01-02T15:04:05Z"))
	if len(mods) > 0 {
		fmt.Fprintf(&sb, "# Requires: ansible-galaxy collection install community.general\n")
	}
	fmt.Fprintf(&sb, "#\n")
	fmt.Fprintf(&sb, "# Usage:\n")
	fmt.Fprintf(&sb, "#   ansible-playbook playbook.yml                     # run on localhost\n")
	fmt.Fprintf(&sb, "#   ansible-playbook playbook.yml -e target=myhost    # run on remote\n\n")

	// ── Play header ───────────────────────────────────────────────────────────
	fmt.Fprintf(&sb, "- name: Restore envsnap environment (%s)\n", snap.Meta.Hostname)
	fmt.Fprintf(&sb, "  hosts: \"{{ target | default('localhost') }}\"\n")
	fmt.Fprintf(&sb, "  become: true\n")

	// ── vars (env) ────────────────────────────────────────────────────────────
	if !opts.SkipEnv && len(snap.Sections.Env) > 0 {
		envVars := filteredEnvVars(snap.Sections.Env, true)
		delete(envVars, "HOME") // machine-specific
		if len(envVars) > 0 {
			fmt.Fprintf(&sb, "\n  vars:\n")
			for _, k := range sortedKeys(envVars) {
				// Ansible convention: lowercase var names.  Keep original uppercase
				// names as comments so users can reference them clearly.
				fmt.Fprintf(&sb, "    %s: %s\n", strings.ToLower(k), yamlQuote(envVars[k]))
			}
		}
	}

	// ── tasks ─────────────────────────────────────────────────────────────────
	fmt.Fprintf(&sb, "\n  tasks:\n")

	// Packages
	if !opts.SkipPackages && len(snap.Sections.Packages) > 0 {
		switch pm {
		case "apt":
			fmt.Fprintf(&sb, "    - name: Update apt cache\n")
			fmt.Fprintf(&sb, "      ansible.builtin.apt:\n")
			fmt.Fprintf(&sb, "        update_cache: true\n")
			fmt.Fprintf(&sb, "        cache_valid_time: 3600\n\n")

			fmt.Fprintf(&sb, "    - name: Install packages via apt (%d total)\n", len(snap.Sections.Packages))
			fmt.Fprintf(&sb, "      # NOTE: list includes all installed packages.\n")
			fmt.Fprintf(&sb, "      # Use --skip-packages and list only what you need.\n")
			fmt.Fprintf(&sb, "      ansible.builtin.apt:\n")
			fmt.Fprintf(&sb, "        name: \"{{ item }}\"\n")
			fmt.Fprintf(&sb, "        state: present\n")
			fmt.Fprintf(&sb, "      loop:\n")
			for _, p := range snap.Sections.Packages {
				fmt.Fprintf(&sb, "        - %s\n", yamlQuote(p.Name))
			}
			fmt.Fprintf(&sb, "\n")

		case "dnf":
			fmt.Fprintf(&sb, "    - name: Install packages via dnf (%d total)\n", len(snap.Sections.Packages))
			fmt.Fprintf(&sb, "      # NOTE: list includes all installed packages.\n")
			fmt.Fprintf(&sb, "      # Use --skip-packages and list only what you need.\n")
			fmt.Fprintf(&sb, "      ansible.builtin.dnf:\n")
			fmt.Fprintf(&sb, "        name: \"{{ item }}\"\n")
			fmt.Fprintf(&sb, "        state: present\n")
			fmt.Fprintf(&sb, "        skip_broken: true\n")
			fmt.Fprintf(&sb, "      loop:\n")
			for _, p := range snap.Sections.Packages {
				fmt.Fprintf(&sb, "        - %s\n", yamlQuote(p.Name))
			}
			fmt.Fprintf(&sb, "\n")

		default:
			fmt.Fprintf(&sb, "    # TODO: install packages — unknown manager %q\n\n", pm)
		}
	}

	// Go toolchain
	if ver != "" {
		arch := goArch(snap)
		tarball := fmt.Sprintf("%s.linux-%s.tar.gz", ver, arch)
		dlURL := "https://go.dev/dl/" + tarball

		fmt.Fprintf(&sb, "    - name: Install Go (%s)\n", ver)
		fmt.Fprintf(&sb, "      block:\n")
		fmt.Fprintf(&sb, "        - name: Download Go tarball\n")
		fmt.Fprintf(&sb, "          ansible.builtin.get_url:\n")
		fmt.Fprintf(&sb, "            url: %s\n", yamlQuote(dlURL))
		fmt.Fprintf(&sb, "            dest: %s\n", yamlQuote("/tmp/"+tarball))
		fmt.Fprintf(&sb, "            mode: \"0644\"\n\n")
		fmt.Fprintf(&sb, "        - name: Remove existing Go installation\n")
		fmt.Fprintf(&sb, "          ansible.builtin.file:\n")
		fmt.Fprintf(&sb, "            path: /usr/local/go\n")
		fmt.Fprintf(&sb, "            state: absent\n\n")
		fmt.Fprintf(&sb, "        - name: Extract Go (%s)\n", ver)
		fmt.Fprintf(&sb, "          ansible.builtin.unarchive:\n")
		fmt.Fprintf(&sb, "            src: %s\n", yamlQuote("/tmp/"+tarball))
		fmt.Fprintf(&sb, "            dest: /usr/local\n")
		fmt.Fprintf(&sb, "            remote_src: true\n")
		fmt.Fprintf(&sb, "            creates: /usr/local/go/bin/go\n\n")
		fmt.Fprintf(&sb, "        - name: Add Go to PATH via /etc/profile.d\n")
		fmt.Fprintf(&sb, "          ansible.builtin.copy:\n")
		fmt.Fprintf(&sb, "            content: \"export PATH=\\\"$PATH:/usr/local/go/bin\\\"\\n\"\n")
		fmt.Fprintf(&sb, "            dest: /etc/profile.d/go.sh\n")
		fmt.Fprintf(&sb, "            mode: \"0644\"\n\n")
	}

	// Kernel modules via modprobe
	if len(mods) > 0 {
		// Modprobe (idempotent via community.general.modprobe)
		fmt.Fprintf(&sb, "    - name: Load kernel modules (%d)\n", len(mods))
		fmt.Fprintf(&sb, "      # community.general.modprobe is idempotent — unlike raw modprobe it\n")
		fmt.Fprintf(&sb, "      # won't fail if the module is already loaded.\n")
		fmt.Fprintf(&sb, "      community.general.modprobe:\n")
		fmt.Fprintf(&sb, "        name: \"{{ item }}\"\n")
		fmt.Fprintf(&sb, "        state: present\n")
		fmt.Fprintf(&sb, "      loop:\n")
		for _, m := range mods {
			fmt.Fprintf(&sb, "        - %s\n", m.Name)
		}
		fmt.Fprintf(&sb, "      ignore_errors: true  # some modules may not be present on all hardware\n\n")

		fmt.Fprintf(&sb, "    - name: Persist kernel modules across reboots\n")
		fmt.Fprintf(&sb, "      ansible.builtin.copy:\n")
		fmt.Fprintf(&sb, "        content: |\n")
		fmt.Fprintf(&sb, "          # envsnap — generated %s\n", date)
		for _, m := range mods {
			fmt.Fprintf(&sb, "          %s\n", m.Name)
		}
		fmt.Fprintf(&sb, "        dest: /etc/modules-load.d/envsnap.conf\n")
		fmt.Fprintf(&sb, "        mode: \"0644\"\n")
		fmt.Fprintf(&sb, "        owner: root\n")
		fmt.Fprintf(&sb, "        group: root\n\n")
	}

	// Env vars: write to /etc/profile.d for system-wide persistence
	if !opts.SkipEnv && len(snap.Sections.Env) > 0 {
		envVars := filteredEnvVars(snap.Sections.Env, true)
		delete(envVars, "HOME")
		delete(envVars, "PATH") // managed by Go install task above
		if len(envVars) > 0 {
			keys := sortedKeys(envVars)
			fmt.Fprintf(&sb, "    - name: Persist environment variables to /etc/profile.d\n")
			fmt.Fprintf(&sb, "      ansible.builtin.copy:\n")
			fmt.Fprintf(&sb, "        content: |\n")
			fmt.Fprintf(&sb, "          # envsnap — generated %s\n", date)
			for _, k := range keys {
				fmt.Fprintf(&sb, "          export %s=%s\n", k, shellQuote(envVars[k]))
			}
			fmt.Fprintf(&sb, "        dest: /etc/profile.d/envsnap-env.sh\n")
			fmt.Fprintf(&sb, "        mode: \"0644\"\n")
			fmt.Fprintf(&sb, "        owner: root\n")
			fmt.Fprintf(&sb, "        group: root\n")
		}
	}

	return sb.String(), nil
}
