package export

import (
	"fmt"
	"sort"
	"strings"

	"github.com/lignumqt/envsnap/internal/snapshot"
)

func renderDockerfile(snap *snapshot.Snapshot, opts Options) (string, error) {
	var sb strings.Builder
	pm := packageManager(snap)

	// ── Header ───────────────────────────────────────────────────────────────
	fmt.Fprintf(&sb, "# Generated by envsnap %s — export --format dockerfile\n", snap.Meta.ToolVersion)
	fmt.Fprintf(&sb, "# Source host: %s  user: %s  captured: %s\n",
		snap.Meta.Hostname, snap.Meta.User,
		snap.Meta.CreatedAt.UTC().Format("2006-01-02T15:04:05Z"))
	fmt.Fprintf(&sb, "# Usage: docker build -t my-env .\n\n")
	fmt.Fprintf(&sb, "FROM %s\n\n", dockerBaseImage(snap.Sections.System))
	fmt.Fprintf(&sb, "LABEL org.opencontainers.image.description=%s\n\n",
		dockerfileQuote("envsnap environment from "+snap.Meta.Hostname))

	// ── Packages ─────────────────────────────────────────────────────────────
	if !opts.SkipPackages && len(snap.Sections.Packages) > 0 {
		pkgNames := make([]string, 0, len(snap.Sections.Packages))
		var skipped []string
		for _, p := range snap.Sections.Packages {
			if isContainerSkippedPackage(p.Name) {
				skipped = append(skipped, p.Name)
			} else {
				pkgNames = append(pkgNames, p.Name)
			}
		}
		sort.Strings(pkgNames)
		sort.Strings(skipped)

		fmt.Fprintf(&sb, "# ── System packages (%d via %s) %s\n",
			len(pkgNames), pm, strings.Repeat("─", max(0, 60-22-len(pm)-len(fmt.Sprint(len(pkgNames))))))
		fmt.Fprintf(&sb, "# NOTE: all installed packages are listed — use --skip-packages for a\n")
		fmt.Fprintf(&sb, "# smaller image and add only the packages you actually need.\n")
		if len(skipped) > 0 {
			fmt.Fprintf(&sb, "# Host-identity packages excluded (conflict with base image): %s\n",
				strings.Join(skipped, ", "))
		}

		switch pm {
		case "apt":
			fmt.Fprintf(&sb, "RUN apt-get update \\\n")
			fmt.Fprintf(&sb, "    && apt-get install -y --no-install-recommends --ignore-missing \\\n")
			for _, name := range pkgNames {
				fmt.Fprintf(&sb, "        %s \\\n", name)
			}
			fmt.Fprintf(&sb, "    && rm -rf /var/lib/apt/lists/*\n\n")
		case "dnf":
			fmt.Fprintf(&sb, "RUN dnf install -y --skip-unavailable \\\n")
			for _, name := range pkgNames {
				fmt.Fprintf(&sb, "    %s \\\n", name)
			}
			fmt.Fprintf(&sb, "    && dnf clean all\n\n")
		default:
			fmt.Fprintf(&sb, "# Unknown package manager %q — add RUN install … manually\n\n", pm)
		}
	}

	// ── Go toolchain ─────────────────────────────────────────────────────────
	if ver := goVersion(snap); ver != "" {
		arch := goArch(snap)
		tarball := fmt.Sprintf("%s.linux-%s.tar.gz", ver, arch)
		dlURL := "https://go.dev/dl/" + tarball

		fmt.Fprintf(&sb, "# ── Go toolchain (%s) %s\n", ver, strings.Repeat("─", max(0, 60-17-len(ver))))
		fmt.Fprintf(&sb, "RUN wget -q %s -O /tmp/%s \\\n", dlURL, tarball)
		fmt.Fprintf(&sb, "    && tar -C /usr/local -xzf /tmp/%s \\\n", tarball)
		fmt.Fprintf(&sb, "    && rm /tmp/%s\n", tarball)
		fmt.Fprintf(&sb, "ENV PATH=\"$PATH:/usr/local/go/bin\"\n\n")
	}

	// ── Environment variables ─────────────────────────────────────────────────
	if !opts.SkipEnv && len(snap.Sections.Env) > 0 {
		envVars := filteredEnvVars(snap.Sections.Env, true)
		// PATH is already handled by the Go install above; HOME is container-specific.
		delete(envVars, "PATH")
		delete(envVars, "HOME")
		if len(envVars) > 0 {
			keys := sortedKeys(envVars)
			fmt.Fprintf(&sb, "# ── Environment variables (%d)\n", len(keys))
			for _, k := range keys {
				fmt.Fprintf(&sb, "ENV %s=%s\n", k, dockerfileQuote(envVars[k]))
			}
			fmt.Fprintf(&sb, "\n")
		}
	}

	// ── Kernel modules ────────────────────────────────────────────────────────
	if !opts.SkipModules {
		mods := activeMods(snap, opts.OnlyLoaded)
		if len(mods) > 0 {
			// Kernel modules cannot be loaded inside a container —
			// document them as comments with host instructions.
			fmt.Fprintf(&sb, "# ── Kernel modules (%d) %s\n", len(mods),
				strings.Repeat("─", max(0, 60-16-len(fmt.Sprint(len(mods))))))
			fmt.Fprintf(&sb, "# These modules run at the HOST kernel level and cannot be loaded\n")
			fmt.Fprintf(&sb, "# inside a container. Run these on the HOST machine instead:\n")
			fmt.Fprintf(&sb, "#\n")
			for _, m := range mods {
				fmt.Fprintf(&sb, "#   sudo modprobe %s\n", m.Name)
			}
			fmt.Fprintf(&sb, "#\n")
			fmt.Fprintf(&sb, "# To persist across reboots:\n")
			for _, m := range mods {
				fmt.Fprintf(&sb, "#   echo '%s' | sudo tee -a /etc/modules-load.d/envsnap.conf\n", m.Name)
			}
			fmt.Fprintf(&sb, "\n")
		}
	}

	return sb.String(), nil
}
