package export

import (
	"fmt"
	"sort"
	"strings"

	"github.com/lignumqt/envsnap/internal/snapshot"
)

func renderScript(snap *snapshot.Snapshot, opts Options) (string, error) {
	var sb strings.Builder

	// ── Header ───────────────────────────────────────────────────────────────
	fmt.Fprintf(&sb, "#!/usr/bin/env bash\n")
	fmt.Fprintf(&sb, "# Generated by envsnap %s — export --format script\n", snap.Meta.ToolVersion)
	fmt.Fprintf(&sb, "# Source host: %s  user: %s  captured: %s\n",
		snap.Meta.Hostname, snap.Meta.User,
		snap.Meta.CreatedAt.UTC().Format("2006-01-02T15:04:05Z"))
	fmt.Fprintf(&sb, "set -euo pipefail\n\n")

	// ── Packages ─────────────────────────────────────────────────────────────
	if !opts.SkipPackages && len(snap.Sections.Packages) > 0 {
		pm := packageManager(snap)
		pkgNames := make([]string, 0, len(snap.Sections.Packages))
		for _, p := range snap.Sections.Packages {
			pkgNames = append(pkgNames, p.Name)
		}
		sort.Strings(pkgNames)

		fmt.Fprintf(&sb, "# ── Packages (%d via %s) ", len(pkgNames), pm)
		fmt.Fprintf(&sb, "%s\n", strings.Repeat("─", max(0, 60-20-len(pm)-len(fmt.Sprint(len(pkgNames))))))
		fmt.Fprintf(&sb, "# NOTE: includes all installed packages (both explicit and auto-pulled\n")
		fmt.Fprintf(&sb, "# dependencies). Use --skip-packages if you only need specific tools.\n")
		fmt.Fprintf(&sb, "echo '==> Installing packages (%s)'\n", pm)

		switch pm {
		case "apt":
			fmt.Fprintf(&sb, "sudo apt-get update -qq\n")
			fmt.Fprintf(&sb, "sudo apt-get install -y --no-install-recommends --ignore-missing \\\n")
			writeBackslashList(&sb, pkgNames, "  ")
		case "dnf":
			fmt.Fprintf(&sb, "sudo dnf install -y --skip-unavailable \\\n")
			writeBackslashList(&sb, pkgNames, "  ")
		default:
			fmt.Fprintf(&sb, "# Unknown package manager %q — install manually:\n", pm)
			for _, name := range pkgNames {
				fmt.Fprintf(&sb, "#   %s\n", name)
			}
		}
		fmt.Fprintf(&sb, "\n")
	}

	// ── Go toolchain ─────────────────────────────────────────────────────────
	if ver := goVersion(snap); ver != "" {
		arch := goArch(snap)
		tarball := fmt.Sprintf("%s.linux-%s.tar.gz", ver, arch)
		dlURL := "https://go.dev/dl/" + tarball

		fmt.Fprintf(&sb, "# ── Go toolchain (%s) %s\n", ver, strings.Repeat("─", max(0, 60-17-len(ver))))
		fmt.Fprintf(&sb, "echo '==> Installing Go (%s)'\n", ver)
		fmt.Fprintf(&sb, "GO_TARBALL=%s\n", shellQuote(tarball))
		fmt.Fprintf(&sb, "wget -q %s -O \"/tmp/${GO_TARBALL}\"\n", shellQuote(dlURL))
		fmt.Fprintf(&sb, "sudo rm -rf /usr/local/go\n")
		fmt.Fprintf(&sb, "sudo tar -C /usr/local -xzf \"/tmp/${GO_TARBALL}\"\n")
		fmt.Fprintf(&sb, "rm \"/tmp/${GO_TARBALL}\"\n")
		fmt.Fprintf(&sb, "export PATH=\"$PATH:/usr/local/go/bin\"\n")
		fmt.Fprintf(&sb, "grep -qxF 'export PATH=\"$PATH:/usr/local/go/bin\"' \"${HOME}/.profile\" 2>/dev/null \\\n")
		fmt.Fprintf(&sb, "  || echo 'export PATH=\"$PATH:/usr/local/go/bin\"' >> \"${HOME}/.profile\"\n\n")
	}

	// ── Kernel modules ────────────────────────────────────────────────────────
	if !opts.SkipModules {
		mods := activeMods(snap, opts.OnlyLoaded)
		if len(mods) > 0 {
			// ── Load all selected modules via modprobe ──────────────────────────
			fmt.Fprintf(&sb, "# ── Kernel modules (%d) %s\n", len(mods), strings.Repeat("─", max(0, 60-16-len(fmt.Sprint(len(mods))))))
			fmt.Fprintf(&sb, "echo '==> Loading kernel modules'\n")
			for _, m := range mods {
				fmt.Fprintf(&sb, "sudo modprobe %s || echo 'warning: modprobe %s failed'\n",
					m.Name, m.Name)
			}
			fmt.Fprintf(&sb, "\n# Persist modules across reboots (systemd)\n")
			fmt.Fprintf(&sb, "sudo mkdir -p /etc/modules-load.d\n")
			fmt.Fprintf(&sb, "sudo tee /etc/modules-load.d/envsnap.conf > /dev/null <<'MODULES_EOF'\n")
			fmt.Fprintf(&sb, "# envsnap — generated %s\n", snap.Meta.CreatedAt.UTC().Format("2006-01-02"))
			for _, m := range mods {
				fmt.Fprintf(&sb, "%s\n", m.Name)
			}
			fmt.Fprintf(&sb, "MODULES_EOF\n\n")
		}
	}

	// ── Environment variables ─────────────────────────────────────────────────
	if !opts.SkipEnv && len(snap.Sections.Env) > 0 {
		envVars := filteredEnvVars(snap.Sections.Env, true)
		if len(envVars) > 0 {
			keys := sortedKeys(envVars)
			fmt.Fprintf(&sb, "# ── Environment variables (%d important, non-sensitive) %s\n",
				len(keys), strings.Repeat("─", max(0, 60-40-len(fmt.Sprint(len(keys))))))
			fmt.Fprintf(&sb, "# Apply to current shell session. Append to ~/.profile to persist.\n")
			for _, k := range keys {
				fmt.Fprintf(&sb, "export %s=%s\n", k, shellQuote(envVars[k]))
			}
			fmt.Fprintf(&sb, "\n")
		}
	}

	fmt.Fprintf(&sb, "echo '✓ Environment setup complete.'\n")
	return sb.String(), nil
}

// writeBackslashList writes a list of package names with bash line-continuation.
//
//	indent pkg1 \
//	indent pkg2 \
//	indent pkgN      ← last line has no backslash
func writeBackslashList(sb *strings.Builder, names []string, indent string) {
	for i, name := range names {
		if i == len(names)-1 {
			fmt.Fprintf(sb, "%s%s\n", indent, name)
		} else {
			fmt.Fprintf(sb, "%s%s \\\n", indent, name)
		}
	}
}
